import { Navbar } from '@/components/Navbar'; import { Footer } from '@/components/Footer'; import { ContactCTA } from '@/components/ContactCTA'; import type { Metadata } from 'next'; import { Inter } from 'next/font/google'; import './globals.css'; const inter = Inter({ subsets: ['latin'] }); export const metadata: Metadata = {
  metadataBase: new URL("https://supersolarfence.com"),
  title: {
    default: "Super Solar Power Fencing Technology",
    template: "%s | Super Solar Power Fencing Technology",
  },
  description:
    "Leading solar fencing company in Coimbatore, Tamil Nadu offering reliable solar power fencing solutions for farms, industries, residential properties, and commercial establishments.",
  keywords: [
    "Super Solar Power Fencing Technology",
    "Super Solar Fence",
    "Super Solar Fencing",
    "solar fencing company in Coimbatore",
    "best solar fencing company in Coimbatore",
    "solar fence installation Coimbatore",
    "solar power fencing Coimbatore",
    "solar fencing contractors Coimbatore",
    "electric solar fencing Coimbatore",
    "farm solar fencing Coimbatore",
    "agricultural solar fencing Coimbatore",
    "solar fencing for farmland",
    "solar fencing for agriculture",
    "solar fencing for farms in Tamil Nadu",
    "solar fence manufacturers Coimbatore",
    "solar fencing suppliers Coimbatore",
    "solar fencing dealers Coimbatore",
    "solar fencing installation services",
    "solar fencing system Tamil Nadu",
    "solar fencing company Tamil Nadu",
    "solar fencing in Tamil Nadu",
    "solar power fencing Tamil Nadu",
    "electric fencing company Tamil Nadu",
    "electric fencing for farms",
    "solar electric fencing system",
    "perimeter security fencing solutions",
    "farm protection fencing",
    "wild animal protection fencing",
    "elephant protection solar fencing",
    "solar fencing for coconut farms",
    "solar fencing for agricultural land",
    "solar fencing for plantations",
    "industrial solar fencing solutions",
    "residential solar fencing systems",
    "commercial solar fencing installation",
    "solar security fence installers",
    "high voltage solar fencing",
    "solar energizer fencing system",
    "solar fence maintenance services",
    "solar fence repair Coimbatore",
    "solar fencing products supplier",
    "GI wire solar fencing",
    "solar fence energizer",
    "solar fence battery charger",
    "solar fencing accessories",
    "solar perimeter security system",
    "best electric fence installer in Tamil Nadu",
    "solar fencing near me",
    "solar fence company near me",
    "Coimbatore solar fencing experts",
    "Tamil Nadu solar fencing experts",
    "India solar fencing solutions",
    "super solar",
    "fencing work",
    "fence work",
    "solar work",
    "super solar",
    "Super solar",
    "super solar coimbatore",
  ],
  alternates: {
    canonical: "/",
  },
  authors: [{ name: "Super Solar Power Fencing Technology" }],
  publisher: "Super Solar Power Fencing Technology",
  creator: 'Super Solar Power Fencing Technology',
  openGraph: {
    type: 'website',
    locale: 'en_IN',
    url: 'https://supersolarfence.com',
    title: 'Super Solar Power Fencing Technology | Premium Solar Security Solutions',
    description: 'Leading provider of high-quality solar fencing materials, solar panels, energizers, and installation services in Coimbatore. Secure your property with reliable solar solutions.',
    siteName: 'Super Solar Power Fencing Technology',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  verification: {
    google: 'duvkusai1FB6GmOSZXffWJzj6E4HTnMvY4BZKgmhSIM',
  },
  icons: { icon: '/fav-icon.svg' }
}; export default function RootLayout({ children }: { children: React.ReactNode }) { return ( <html lang='en'><body className={`${inter.className} pt-[calc(3.5rem+env(safe-area-inset-top))] pb-[calc(6.5rem+env(safe-area-inset-bottom))] md:pt-0 md:pb-0`}> <Navbar /> <main className='min-h-screen'>{children}</main> <ContactCTA /> <Footer /> </body></html> ); }
